import type { EdgeKind } from "./types";

export interface ReferenceNodeMetadata {
  id: string;
  label: string;
  line1: string;
  line2?: string;
  runs: number;
  iconName:
    | "MessageSquare"
    | "MessageCircle"
    | "HelpCircle"
    | "Database"
    | "FileCheck"
    | "Package"
    | "CreditCard"
    | "AlertTriangle"
    | "Mail"
    | "CheckCircle"
    | "UserCheck"
    | "Clock"
    | "XCircle"
    | "ShieldAlert";
  stateId: string;
  type: string;
  category: string;
  firstSeen: string;
  lastSeen: string;
  totalRuns: number;
  successRate: string;
  description: string;
  isFailure?: boolean;
  position: { x: number; y: number };
  coverage: string;
  coverageDetail: string;
  riskScore: number;
  riskLevel: "Low" | "Medium" | "High";
  stability: string;
  transitions: {
    action: string;
    toId: string;
    label: string;
    count: number;
    percent: string;
    kind: EdgeKind;
  }[];
  selectedAction: {
    name: string;
    description: string;
    usedIn: string;
    successRate: string;
    avgLatency: string;
  };
}

export interface ReferenceEdge {
  id: string;
  from: string;
  to: string;
  sourceHandle?: "top" | "bottom" | "left" | "right";
  targetHandle?: "top" | "bottom" | "left" | "right";
  action?: string;
  kind: EdgeKind;
  runs?: number;
  percent?: string;
}

export interface TraceStep {
  id: string;
  nodeId: string;
  label: string;
  time: string;
  status: "success" | "warning" | "error";
}

export interface ReferenceTraceData {
  runId: string;
  timestamp: string;
  stateCount: number;
  duration: string;
  status: "Success" | "Failed";
  steps: TraceStep[];
}

/* ========================================================================= */
/*  1. SRE AGENT DATASET (Autonomous CloudWatch Remediation)                 */
/* ========================================================================= */

export const SRE_AGENT_NODES: Record<string, ReferenceNodeMetadata> = {
  service_degraded: {
    id: "service_degraded",
    label: "SERVICE DEGRADED",
    line1: "SERVICE",
    line2: "DEGRADED",
    runs: 1248,
    iconName: "AlertTriangle",
    stateId: "S_SERVICE_DEGRADED",
    type: "Inbound",
    category: "Alarm",
    firstSeen: "Sep 18, 2026 08:20",
    lastSeen: "Sep 20, 2026 14:01",
    totalRuns: 1248,
    successRate: "99.8%",
    isFailure: true,
    description: "CloudWatch checkout 5xx anomaly alarm triggered by canary breach.",
    position: { x: 60, y: 370 },
    coverage: "99.8%",
    coverageDetail: "(1,245 / 1,248 runs)",
    riskScore: 0.88,
    riskLevel: "High",
    stability: "-3.2%",
    transitions: [
      { action: "GET HEALTH", toId: "health_inspected", label: "GET HEALTH", count: 892, percent: "71.5%", kind: "observed" },
      { action: "CPU SPIKE", toId: "metric_anomaly", label: "CPU SPIKE", count: 118, percent: "9.5%", kind: "predicted" },
    ],
    selectedAction: {
      name: "receive_alarm",
      description: "Ingests CloudWatch synthetic alarm payload.",
      usedIn: "1,248 runs",
      successRate: "99.9%",
      avgLatency: "45ms",
    },
  },
  metric_anomaly: {
    id: "metric_anomaly",
    label: "METRIC ANOMALY",
    line1: "METRIC",
    line2: "ANOMALY",
    runs: 118,
    iconName: "ShieldAlert",
    stateId: "S_METRIC_ANOMALY",
    type: "Branch",
    category: "Telemetry",
    firstSeen: "Sep 19, 2026 14:02",
    lastSeen: "Sep 20, 2026 11:22",
    totalRuns: 118,
    successRate: "94.2%",
    description: "High CPU & container memory pressure correlating with checkout latency.",
    position: { x: 190, y: 550 },
    coverage: "88.5%",
    coverageDetail: "(104 / 118 runs)",
    riskScore: 0.45,
    riskLevel: "Medium",
    stability: "+1.0%",
    transitions: [
      { action: "GET HEALTH", toId: "health_inspected", label: "GET HEALTH", count: 96, percent: "81.4%", kind: "observed" },
    ],
    selectedAction: {
      name: "query_container_metrics",
      description: "Polls ECS/EKS container cgroup telemetry.",
      usedIn: "118 runs",
      successRate: "98.3%",
      avgLatency: "140ms",
    },
  },
  health_inspected: {
    id: "health_inspected",
    label: "HEALTH INSPECTED",
    line1: "HEALTH",
    line2: "INSPECTED",
    runs: 892,
    iconName: "Database",
    stateId: "S_HEALTH_INSPECTED",
    type: "Process",
    category: "Diagnostics",
    firstSeen: "Sep 18, 2026 08:21",
    lastSeen: "Sep 20, 2026 14:01",
    totalRuns: 892,
    successRate: "91.3%",
    description: "Alarms confirm checkout is unhealthy on active cluster nodes.",
    position: { x: 240, y: 370 },
    coverage: "94.2%",
    coverageDetail: "(840 / 892 runs)",
    riskScore: 0.12,
    riskLevel: "Low",
    stability: "+3.2%",
    transitions: [
      { action: "QUERY LOGS", toId: "logs_queried", label: "QUERY LOGS", count: 664, percent: "74.4%", kind: "observed" },
      { action: "CHECK CANARY", toId: "canary_alert", label: "CHECK CANARY", count: 180, percent: "20.2%", kind: "predicted" },
    ],
    selectedAction: {
      name: "get_service_health",
      description: "Reads service health check endpoints and response codes.",
      usedIn: "892 runs",
      successRate: "96.4%",
      avgLatency: "110ms",
    },
  },
  canary_alert: {
    id: "canary_alert",
    label: "CANARY ALERT",
    line1: "CANARY",
    line2: "ALERT",
    runs: 421,
    iconName: "AlertTriangle",
    stateId: "S_CANARY_ALERT",
    type: "Action",
    category: "Verification",
    firstSeen: "Sep 19, 2026 09:15",
    lastSeen: "Sep 20, 2026 12:40",
    totalRuns: 421,
    successRate: "88.1%",
    description: "Synthetic canary tests failing on checkout transaction endpoint.",
    position: { x: 250, y: 180 },
    coverage: "86.4%",
    coverageDetail: "(364 / 421 runs)",
    riskScore: 0.65,
    riskLevel: "Medium",
    stability: "-0.5%",
    transitions: [
      { action: "QUERY LOGS", toId: "logs_queried", label: "QUERY LOGS", count: 350, percent: "83.1%", kind: "observed" },
    ],
    selectedAction: {
      name: "poll_canary_status",
      description: "Evaluates CloudWatch synthetic canary failure stack.",
      usedIn: "421 runs",
      successRate: "92.0%",
      avgLatency: "150ms",
    },
  },
  logs_queried: {
    id: "logs_queried",
    label: "LOGS QUERIED",
    line1: "LOGS",
    line2: "QUERIED",
    runs: 664,
    iconName: "FileCheck",
    stateId: "S_LOGS_QUERIED",
    type: "Process",
    category: "Diagnostics",
    firstSeen: "Sep 18, 2026 08:25",
    lastSeen: "Sep 20, 2026 14:02",
    totalRuns: 664,
    successRate: "95.6%",
    description: "Structured log filter points to runtime exception in checkout container.",
    position: { x: 420, y: 370 },
    coverage: "96.1%",
    coverageDetail: "(638 / 664 runs)",
    riskScore: 0.08,
    riskLevel: "Low",
    stability: "+1.8%",
    transitions: [
      { action: "AUTOSCALE CHECK", toId: "autoscale_check", label: "AUTOSCALE CHECK", count: 521, percent: "78.5%", kind: "observed" },
      { action: "POD HEALTH", toId: "pod_health", label: "POD HEALTH", count: 654, percent: "98.5%", kind: "observed" },
    ],
    selectedAction: {
      name: "query_service_logs",
      description: "Executes CloudWatch Logs Insights query for fatal stacktraces.",
      usedIn: "664 runs",
      successRate: "98.1%",
      avgLatency: "95ms",
    },
  },
  pod_health: {
    id: "pod_health",
    label: "POD HEALTH",
    line1: "POD",
    line2: "HEALTH",
    runs: 654,
    iconName: "Database",
    stateId: "S_POD_HEALTH",
    type: "Process",
    category: "Infrastructure",
    firstSeen: "Sep 18, 2026 08:30",
    lastSeen: "Sep 20, 2026 13:58",
    totalRuns: 654,
    successRate: "97.2%",
    description: "Node cluster capacity normal; issue isolated to app deployment layer.",
    position: { x: 440, y: 560 },
    coverage: "95.8%",
    coverageDetail: "(627 / 654 runs)",
    riskScore: 0.06,
    riskLevel: "Low",
    stability: "+0.8%",
    transitions: [
      { action: "ROLLBACK OK", toId: "rollback_succeeded", label: "ROLLBACK OK", count: 610, percent: "93.3%", kind: "observed" },
    ],
    selectedAction: {
      name: "get_cluster_nodes",
      description: "Verifies cluster compute capacity and kubelet health.",
      usedIn: "654 runs",
      successRate: "98.8%",
      avgLatency: "115ms",
    },
  },
  autoscale_check: {
    id: "autoscale_check",
    label: "AUTOSCALE CHECK",
    line1: "AUTOSCALE",
    line2: "CHECK",
    runs: 521,
    iconName: "Package",
    stateId: "S_AUTOSCALE_CHECK",
    type: "Decision",
    category: "Infrastructure",
    firstSeen: "Sep 19, 2026 10:11",
    lastSeen: "Sep 20, 2026 13:30",
    totalRuns: 521,
    successRate: "96.4%",
    description: "Autoscale thresholds evaluated; confirms error is not traffic surge.",
    position: { x: 440, y: 180 },
    coverage: "94.6%",
    coverageDetail: "(493 / 521 runs)",
    riskScore: 0.11,
    riskLevel: "Low",
    stability: "+0.2%",
    transitions: [
      { action: "BAD DEPLOY", toId: "bad_deployment_identified", label: "BAD DEPLOY", count: 312, percent: "59.9%", kind: "predicted" },
      { action: "TRIGGER ROLLBACK", toId: "rollback_succeeded", label: "TRIGGER ROLLBACK", count: 180, percent: "34.5%", kind: "observed" },
    ],
    selectedAction: {
      name: "evaluate_autoscaling_policy",
      description: "Queries target tracking alarms and minimum capacity.",
      usedIn: "521 runs",
      successRate: "97.5%",
      avgLatency: "85ms",
    },
  },
  bad_deployment_identified: {
    id: "bad_deployment_identified",
    label: "BAD DEPLOY",
    line1: "BAD",
    line2: "DEPLOY",
    runs: 312,
    iconName: "Package",
    stateId: "S_BAD_DEPLOY",
    type: "Action",
    category: "Release",
    firstSeen: "Sep 19, 2026 11:00",
    lastSeen: "Sep 20, 2026 14:02",
    totalRuns: 312,
    successRate: "89.4%",
    description: "Active version v1.8.3-bad identified as source. Last-known-good is v1.8.2.",
    position: { x: 670, y: 180 },
    coverage: "88.1%",
    coverageDetail: "(275 / 312 runs)",
    riskScore: 0.35,
    riskLevel: "Medium",
    stability: "-1.1%",
    transitions: [
      { action: "VERIFY SERVICE", toId: "verify_service", label: "VERIFY SERVICE", count: 210, percent: "67.3%", kind: "predicted" },
      { action: "ROLLBACK DEPLOYMENT", toId: "rollback_succeeded", label: "ROLLBACK DEPLOYMENT", count: 95, percent: "30.4%", kind: "predicted" },
    ],
    selectedAction: {
      name: "get_deployment_history",
      description: "Retrieves deployment commits, image tags, and pipeline metadata.",
      usedIn: "312 runs",
      successRate: "94.2%",
      avgLatency: "70ms",
    },
  },
  rollback_succeeded: {
    id: "rollback_succeeded",
    label: "ROLLBACK OK",
    line1: "ROLLBACK",
    line2: "OK",
    runs: 428,
    iconName: "CheckCircle",
    stateId: "S_ROLLBACK_OK",
    type: "Remediation",
    category: "Remediation",
    firstSeen: "Sep 18, 2026 09:00",
    lastSeen: "Sep 20, 2026 14:03",
    totalRuns: 428,
    successRate: "98.0%",
    description: "Rollback applied. Last-known-good version v1.8.2 activated on cluster.",
    position: { x: 550, y: 380 },
    coverage: "96.4%",
    coverageDetail: "(413 / 428 runs)",
    riskScore: 0.08,
    riskLevel: "Low",
    stability: "+0.4%",
    transitions: [
      { action: "APPLY PATCH", toId: "remediation_in_progress", label: "APPLY PATCH", count: 312, percent: "72.9%", kind: "observed" },
      { action: "ROLLBACK TIMEOUT", toId: "rollback_timeout", label: "ROLLBACK TIMEOUT", count: 87, percent: "20.3%", kind: "verified" },
      { action: "ESCALATE ONCALL", toId: "escalate_oncall", label: "ESCALATE ONCALL", count: 18, percent: "4.2%", kind: "predicted" },
      { action: "DOUBLE ROLLBACK", toId: "double_rollback", label: "DOUBLE ROLLBACK", count: 6, percent: "1.4%", kind: "verified" },
      { action: "STALE HEALTH", toId: "stale_health", label: "STALE HEALTH", count: 5, percent: "1.2%", kind: "protected" },
    ],
    selectedAction: {
      name: "rollback_deployment",
      description: "Executes atomic deployment rollback to last known good tag.",
      usedIn: "428 runs",
      successRate: "98.0%",
      avgLatency: "310ms",
    },
  },
  remediation_in_progress: {
    id: "remediation_in_progress",
    label: "APPLY PATCH",
    line1: "APPLY",
    line2: "PATCH",
    runs: 310,
    iconName: "Clock",
    stateId: "S_APPLY_PATCH",
    type: "Process",
    category: "Remediation",
    firstSeen: "Sep 18, 2026 09:12",
    lastSeen: "Sep 20, 2026 14:03",
    totalRuns: 310,
    successRate: "96.8%",
    description: "Hotfix configuration synced and DNS routing switched to healthy pods.",
    position: { x: 740, y: 380 },
    coverage: "97.1%",
    coverageDetail: "(301 / 310 runs)",
    riskScore: 0.14,
    riskLevel: "Low",
    stability: "+2.1%",
    transitions: [
      { action: "VERIFY SERVICE", toId: "verify_service", label: "VERIFY SERVICE", count: 285, percent: "91.9%", kind: "observed" },
      { action: "ROLLBACK TIMEOUT", toId: "rollback_timeout", label: "ROLLBACK TIMEOUT", count: 15, percent: "4.8%", kind: "verified" },
      { action: "STALE HEALTH", toId: "stale_health", label: "STALE HEALTH", count: 10, percent: "3.2%", kind: "protected" },
    ],
    selectedAction: {
      name: "sync_hotfix_config",
      description: "Pushes runtime configuration flag overrides.",
      usedIn: "310 runs",
      successRate: "98.4%",
      avgLatency: "190ms",
    },
  },
  verify_service: {
    id: "verify_service",
    label: "VERIFY SERVICE",
    line1: "VERIFY",
    line2: "SERVICE",
    runs: 389,
    iconName: "CheckCircle",
    stateId: "S_VERIFY_SERVICE",
    type: "Action",
    category: "Verification",
    firstSeen: "Sep 18, 2026 09:20",
    lastSeen: "Sep 20, 2026 14:04",
    totalRuns: 389,
    successRate: "99.2%",
    description: "Post-rollback health validation check executing live synthetic transactions.",
    position: { x: 910, y: 180 },
    coverage: "98.5%",
    coverageDetail: "(383 / 389 runs)",
    riskScore: 0.04,
    riskLevel: "Low",
    stability: "+0.3%",
    transitions: [
      { action: "SERVICE RESTORED", toId: "service_restored", label: "SERVICE RESTORED", count: 385, percent: "99.0%", kind: "observed" },
    ],
    selectedAction: {
      name: "verify_service",
      description: "Validates HTTP 200 responses and latency SLA compliance.",
      usedIn: "389 runs",
      successRate: "99.5%",
      avgLatency: "80ms",
    },
  },
  service_restored: {
    id: "service_restored",
    label: "SERVICE RESTORED",
    line1: "SERVICE",
    line2: "RESTORED",
    runs: 435,
    iconName: "CheckCircle",
    stateId: "S_SERVICE_RESTORED",
    type: "Terminal",
    category: "Resolution",
    firstSeen: "Sep 18, 2026 09:25",
    lastSeen: "Sep 20, 2026 14:05",
    totalRuns: 435,
    successRate: "100.0%",
    description: "Outage resolved. Checkout SLA restored to 99.99%. Incident archived.",
    position: { x: 930, y: 380 },
    coverage: "99.5%",
    coverageDetail: "(433 / 435 runs)",
    riskScore: 0.01,
    riskLevel: "Low",
    stability: "+0.1%",
    transitions: [],
    selectedAction: {
      name: "close_incident",
      description: "Generates resolution telemetry and closes incident timeline.",
      usedIn: "435 runs",
      successRate: "100%",
      avgLatency: "65ms",
    },
  },
  rollback_timeout: {
    id: "rollback_timeout",
    label: "ROLLBACK TIMEOUT",
    line1: "ROLLBACK",
    line2: "TIMEOUT",
    runs: 87,
    iconName: "Clock",
    stateId: "S_ROLLBACK_TIMEOUT",
    type: "Failure",
    category: "Failure",
    firstSeen: "Sep 19, 2026 15:30",
    lastSeen: "Sep 20, 2026 13:45",
    totalRuns: 87,
    successRate: "0.0%",
    isFailure: true,
    description: "Rollback tool timed out after applying payload; client lacks idempotency token.",
    position: { x: 700, y: 580 },
    coverage: "74.7%",
    coverageDetail: "(65 / 87 runs)",
    riskScore: 0.82,
    riskLevel: "High",
    stability: "-4.2%",
    transitions: [
      { action: "DOUBLE ROLLBACK", toId: "double_rollback", label: "DOUBLE ROLLBACK", count: 48, percent: "55.2%", kind: "verified" },
      { action: "ESCALATE ONCALL", toId: "escalate_oncall", label: "ESCALATE ONCALL", count: 32, percent: "36.8%", kind: "predicted" },
    ],
    selectedAction: {
      name: "retry_rollback_without_token",
      description: "Unsafe rollback retry attempt after timeout error.",
      usedIn: "87 runs",
      successRate: "0%",
      avgLatency: "320ms",
    },
  },
  double_rollback: {
    id: "double_rollback",
    label: "DOUBLE ROLLBACK",
    line1: "DOUBLE",
    line2: "ROLLBACK",
    runs: 60,
    iconName: "XCircle",
    stateId: "S_DOUBLE_ROLLBACK",
    type: "Failure",
    category: "Regression",
    firstSeen: "Sep 19, 2026 16:10",
    lastSeen: "Sep 20, 2026 12:15",
    totalRuns: 60,
    successRate: "0.0%",
    isFailure: true,
    description: "Invariant violation: agent overshot and rolled back to archaic v1.8.1.",
    position: { x: 590, y: 700 },
    coverage: "68.3%",
    coverageDetail: "(41 / 60 runs)",
    riskScore: 0.95,
    riskLevel: "High",
    stability: "-8.5%",
    transitions: [
      { action: "ESCALATE ONCALL", toId: "escalate_oncall", label: "ESCALATE ONCALL", count: 58, percent: "96.7%", kind: "predicted" },
    ],
    selectedAction: {
      name: "rollback_count_guard",
      description: "Permanent eval assertion: rollback_count <= 1.",
      usedIn: "60 runs",
      successRate: "0%",
      avgLatency: "45ms",
    },
  },
  escalate_oncall: {
    id: "escalate_oncall",
    label: "ESCALATE ONCALL",
    line1: "ESCALATE",
    line2: "ONCALL",
    runs: 276,
    iconName: "UserCheck",
    stateId: "S_ESCALATE_ONCALL",
    type: "Action",
    category: "Escalation",
    firstSeen: "Sep 18, 2026 12:44",
    lastSeen: "Sep 20, 2026 11:30",
    totalRuns: 276,
    successRate: "82.6%",
    description: "Autonomous policy handoff to human Site Reliability Engineer on PagerDuty.",
    position: { x: 440, y: 700 },
    coverage: "84.1%",
    coverageDetail: "(232 / 276 runs)",
    riskScore: 0.48,
    riskLevel: "Medium",
    stability: "-1.2%",
    transitions: [
      { action: "SERVICE RESTORED", toId: "service_restored", label: "SERVICE RESTORED", count: 228, percent: "82.6%", kind: "observed" },
    ],
    selectedAction: {
      name: "page_oncall_engineer",
      description: "Pages SRE team via PagerDuty webhook with trace context.",
      usedIn: "276 runs",
      successRate: "98.9%",
      avgLatency: "250ms",
    },
  },
  stale_health: {
    id: "stale_health",
    label: "STALE HEALTH",
    line1: "STALE",
    line2: "HEALTH",
    runs: 102,
    iconName: "AlertTriangle",
    stateId: "S_STALE_HEALTH",
    type: "Protected",
    category: "Safety",
    firstSeen: "Sep 19, 2026 14:20",
    lastSeen: "Sep 20, 2026 12:00",
    totalRuns: 102,
    successRate: "0.0%",
    isFailure: true,
    description: "Cached TTL health check falsely reported 200 before pods finished booting.",
    position: { x: 890, y: 560 },
    coverage: "95.1%",
    coverageDetail: "(97 / 102 runs)",
    riskScore: 0.72,
    riskLevel: "High",
    stability: "-2.5%",
    transitions: [
      { action: "SERVICE RESTORED", toId: "service_restored", label: "SERVICE RESTORED", count: 98, percent: "96.1%", kind: "predicted" },
    ],
    selectedAction: {
      name: "bypass_cached_health",
      description: "Forces cache-busting on synthetic health probes.",
      usedIn: "102 runs",
      successRate: "94.0%",
      avgLatency: "80ms",
    },
  },
};

export const SRE_AGENT_EDGES: ReferenceEdge[] = [
  // Intake & Alarm flows
  { id: "e1", from: "service_degraded", to: "health_inspected", sourceHandle: "right", targetHandle: "left", kind: "observed", action: "GET HEALTH" },
  { id: "e2", from: "service_degraded", to: "metric_anomaly", sourceHandle: "bottom", targetHandle: "top", kind: "predicted", action: "CPU SPIKE" },
  { id: "e3", from: "metric_anomaly", to: "health_inspected", sourceHandle: "top", targetHandle: "bottom", kind: "observed", action: "GET HEALTH" },

  // Diagnostics & Canary
  { id: "e4", from: "health_inspected", to: "canary_alert", sourceHandle: "top", targetHandle: "bottom", kind: "predicted", action: "CHECK CANARY" },
  { id: "e5", from: "health_inspected", to: "logs_queried", sourceHandle: "right", targetHandle: "left", kind: "observed", action: "QUERY LOGS" },
  { id: "e6", from: "canary_alert", to: "logs_queried", sourceHandle: "right", targetHandle: "top", kind: "predicted", action: "QUERY LOGS" },

  // Logs & Pod Health
  { id: "e7", from: "logs_queried", to: "autoscale_check", sourceHandle: "top", targetHandle: "left", kind: "observed", action: "AUTOSCALE CHECK" },
  { id: "e8", from: "logs_queried", to: "pod_health", sourceHandle: "bottom", targetHandle: "top", kind: "observed", action: "POD HEALTH" },
  { id: "e9", from: "pod_health", to: "rollback_succeeded", sourceHandle: "right", targetHandle: "left", kind: "observed", action: "ROLLBACK OK" },

  // Autoscale & Bad Deploy Identification
  { id: "e10", from: "autoscale_check", to: "bad_deployment_identified", sourceHandle: "right", targetHandle: "left", kind: "predicted", action: "BAD DEPLOY" },
  { id: "e11", from: "autoscale_check", to: "rollback_succeeded", sourceHandle: "bottom", targetHandle: "top", kind: "observed", action: "TRIGGER ROLLBACK" },
  { id: "e12", from: "bad_deployment_identified", to: "verify_service", sourceHandle: "right", targetHandle: "left", kind: "predicted", action: "VERIFY SERVICE" },
  { id: "e13", from: "bad_deployment_identified", to: "rollback_succeeded", sourceHandle: "bottom", targetHandle: "top", kind: "predicted", action: "ROLLBACK DEPLOYMENT" },

  // Central Hub: ROLLBACK OK
  { id: "e14", from: "rollback_succeeded", to: "remediation_in_progress", sourceHandle: "right", targetHandle: "left", kind: "observed", runs: 312, percent: "72.9%", action: "APPLY PATCH" },
  { id: "e15", from: "rollback_succeeded", to: "rollback_timeout", sourceHandle: "bottom", targetHandle: "top", kind: "verified", runs: 87, percent: "20.3%", action: "ROLLBACK TIMEOUT" },
  { id: "e16", from: "rollback_succeeded", to: "escalate_oncall", sourceHandle: "bottom", targetHandle: "top", kind: "predicted", runs: 18, percent: "4.2%", action: "ESCALATE ONCALL" },
  { id: "e17", from: "rollback_succeeded", to: "double_rollback", sourceHandle: "bottom", targetHandle: "top", kind: "verified", runs: 6, percent: "1.4%", action: "DOUBLE ROLLBACK" },
  { id: "e18", from: "rollback_succeeded", to: "stale_health", sourceHandle: "bottom", targetHandle: "left", kind: "protected", runs: 5, percent: "1.2%", action: "STALE HEALTH" },

  // Remediation to Verification & Danger
  { id: "e19", from: "remediation_in_progress", to: "verify_service", sourceHandle: "top", targetHandle: "bottom", kind: "observed", action: "VERIFY SERVICE" },
  { id: "e20", from: "remediation_in_progress", to: "rollback_timeout", sourceHandle: "bottom", targetHandle: "top", kind: "verified", action: "TIMEOUT" },
  { id: "e21", from: "remediation_in_progress", to: "stale_health", sourceHandle: "bottom", targetHandle: "top", kind: "protected", action: "STALE HEALTH" },

  // Terminal & Escalation Paths
  { id: "e22", from: "verify_service", to: "service_restored", sourceHandle: "bottom", targetHandle: "top", kind: "observed", action: "SERVICE RESTORED" },
  { id: "e23", from: "stale_health", to: "service_restored", sourceHandle: "top", targetHandle: "bottom", kind: "predicted", action: "RESTORE" },
  { id: "e24", from: "rollback_timeout", to: "double_rollback", sourceHandle: "bottom", targetHandle: "top", kind: "verified", action: "BLIND RETRY" },
  { id: "e25", from: "rollback_timeout", to: "escalate_oncall", sourceHandle: "bottom", targetHandle: "right", kind: "predicted", action: "PAGE SRE" },
  { id: "e26", from: "double_rollback", to: "escalate_oncall", sourceHandle: "left", targetHandle: "right", kind: "predicted", action: "MANUAL INTERVENTION" },
  { id: "e27", from: "escalate_oncall", to: "service_restored", sourceHandle: "right", targetHandle: "bottom", kind: "observed", action: "HOTFIX APPLIED" },
];

export const SRE_AGENT_TRACE: ReferenceTraceData = {
  runId: "tr_84f2",
  timestamp: "Sep 20, 2026 14:26:41",
  stateCount: 7,
  duration: "42.6s",
  status: "Success",
  steps: [
    { id: "s1", nodeId: "service_degraded", label: "SERVICE DEGRADED", time: "0.0s", status: "warning" },
    { id: "s2", nodeId: "health_inspected", label: "HEALTH INSPECTED", time: "1.2s", status: "success" },
    { id: "s3", nodeId: "logs_queried", label: "LOGS QUERIED", time: "3.4s", status: "success" },
    { id: "s4", nodeId: "bad_deployment_identified", label: "BAD DEPLOY", time: "5.1s", status: "success" },
    { id: "s5", nodeId: "rollback_succeeded", label: "ROLLBACK OK", time: "8.7s", status: "success" },
    { id: "s6", nodeId: "verify_service", label: "VERIFY SERVICE", time: "28.1s", status: "success" },
    { id: "s7", nodeId: "service_restored", label: "SERVICE RESTORED", time: "42.6s", status: "success" },
  ],
};

/* ========================================================================= */
/*  2. CUSTOMER SUPPORT AGENT DATASET (Refund Dialogue Workflow)             */
/* ========================================================================= */

export const CUSTOMER_SUPPORT_NODES: Record<string, ReferenceNodeMetadata> = {
  user_request: {
    id: "user_request",
    label: "USER REQUEST",
    line1: "USER",
    line2: "REQUEST",
    runs: 1248,
    iconName: "MessageSquare",
    stateId: "S_USER_REQUEST",
    type: "Inbound",
    category: "Inbound",
    firstSeen: "Apr 18, 2025 08:20",
    lastSeen: "Apr 28, 2025 13:01",
    totalRuns: 1248,
    successRate: "99.8%",
    description: "Initial customer support refund request received via chat interface.",
    position: { x: 60, y: 370 },
    coverage: "99.8%",
    coverageDetail: "(1,245 / 1,248 runs)",
    riskScore: 0.02,
    riskLevel: "Low",
    stability: "+0.1%",
    transitions: [
      { action: "CLASSIFY INTENT", toId: "classify_intent", label: "CLASSIFY INTENT", count: 892, percent: "71.5%", kind: "observed" },
      { action: "SMALL TALK", toId: "small_talk", label: "SMALL TALK", count: 118, percent: "9.5%", kind: "predicted" },
    ],
    selectedAction: {
      name: "receive_payload",
      description: "Ingests user request and parses intent context.",
      usedIn: "1,248 runs",
      successRate: "99.9%",
      avgLatency: "45ms",
    },
  },
  small_talk: {
    id: "small_talk",
    label: "SMALL TALK",
    line1: "SMALL",
    line2: "TALK",
    runs: 118,
    iconName: "MessageSquare",
    stateId: "S_SMALL_TALK",
    type: "Branch",
    category: "Dialogue",
    firstSeen: "Apr 19, 2025 14:02",
    lastSeen: "Apr 28, 2025 11:22",
    totalRuns: 118,
    successRate: "94.2%",
    description: "Casual conversation greeting prior to refund processing.",
    position: { x: 190, y: 550 },
    coverage: "88.5%",
    coverageDetail: "(104 / 118 runs)",
    riskScore: 0.05,
    riskLevel: "Low",
    stability: "+1.0%",
    transitions: [
      { action: "CLASSIFY INTENT", toId: "classify_intent", label: "CLASSIFY INTENT", count: 96, percent: "81.4%", kind: "observed" },
    ],
    selectedAction: {
      name: "generate_greeting",
      description: "Greets customer and requests refund details.",
      usedIn: "118 runs",
      successRate: "98.3%",
      avgLatency: "180ms",
    },
  },
  classify_intent: {
    id: "classify_intent",
    label: "CLASSIFY INTENT",
    line1: "CLASSIFY",
    line2: "INTENT",
    runs: 892,
    iconName: "MessageSquare",
    stateId: "S_CLASSIFY_INTENT",
    type: "Process",
    category: "NLU",
    firstSeen: "Apr 18, 2025 08:21",
    lastSeen: "Apr 28, 2025 13:01",
    totalRuns: 892,
    successRate: "91.3%",
    description: "Extracts order ID, item name, and refund reason from dialogue.",
    position: { x: 240, y: 370 },
    coverage: "94.2%",
    coverageDetail: "(840 / 892 runs)",
    riskScore: 0.12,
    riskLevel: "Low",
    stability: "+3.2%",
    transitions: [
      { action: "LOOKUP ORDER", toId: "lookup_order", label: "LOOKUP ORDER", count: 664, percent: "74.4%", kind: "observed" },
      { action: "ASK CLARIFICATION", toId: "ask_clarification", label: "ASK CLARIFICATION", count: 180, percent: "20.2%", kind: "predicted" },
    ],
    selectedAction: {
      name: "extract_entities",
      description: "Extracts order ID and validation parameters.",
      usedIn: "892 runs",
      successRate: "96.4%",
      avgLatency: "210ms",
    },
  },
  ask_clarification: {
    id: "ask_clarification",
    label: "ASK CLARIFICATION",
    line1: "ASK",
    line2: "CLARIFICATION",
    runs: 421,
    iconName: "HelpCircle",
    stateId: "S_ASK_CLARIFICATION",
    type: "Action",
    category: "Dialogue",
    firstSeen: "Apr 20, 2025 09:15",
    lastSeen: "Apr 28, 2025 12:40",
    totalRuns: 421,
    successRate: "88.1%",
    description: "Prompts user for missing order identifier or clarification.",
    position: { x: 250, y: 180 },
    coverage: "86.4%",
    coverageDetail: "(364 / 421 runs)",
    riskScore: 0.18,
    riskLevel: "Low",
    stability: "-0.5%",
    transitions: [
      { action: "LOOKUP ORDER", toId: "lookup_order", label: "LOOKUP ORDER", count: 350, percent: "83.1%", kind: "observed" },
    ],
    selectedAction: {
      name: "prompt_order_id",
      description: "Generates clarifying response for customer.",
      usedIn: "421 runs",
      successRate: "92.0%",
      avgLatency: "150ms",
    },
  },
  lookup_order: {
    id: "lookup_order",
    label: "LOOKUP ORDER",
    line1: "LOOKUP",
    line2: "ORDER",
    runs: 664,
    iconName: "Database",
    stateId: "S_LOOKUP_ORDER",
    type: "Process",
    category: "Database",
    firstSeen: "Apr 18, 2025 08:25",
    lastSeen: "Apr 28, 2025 13:02",
    totalRuns: 664,
    successRate: "95.6%",
    description: "Queries order management system for invoice and delivery state.",
    position: { x: 420, y: 370 },
    coverage: "96.1%",
    coverageDetail: "(638 / 664 runs)",
    riskScore: 0.08,
    riskLevel: "Low",
    stability: "+1.8%",
    transitions: [
      { action: "VERIFY ELIGIBILITY", toId: "verify_eligibility", label: "VERIFY ELIGIBILITY", count: 521, percent: "78.5%", kind: "observed" },
      { action: "LOOKUP CUSTOMER", toId: "lookup_customer", label: "LOOKUP CUSTOMER", count: 654, percent: "98.5%", kind: "observed" },
    ],
    selectedAction: {
      name: "query_order_db",
      description: "Reads order table by order_id from database.",
      usedIn: "664 runs",
      successRate: "98.1%",
      avgLatency: "95ms",
    },
  },
  lookup_customer: {
    id: "lookup_customer",
    label: "LOOKUP CUSTOMER",
    line1: "LOOKUP",
    line2: "CUSTOMER",
    runs: 654,
    iconName: "Database",
    stateId: "S_LOOKUP_CUSTOMER",
    type: "Process",
    category: "Database",
    firstSeen: "Apr 18, 2025 08:30",
    lastSeen: "Apr 28, 2025 12:58",
    totalRuns: 654,
    successRate: "97.2%",
    description: "Retrieves customer tier, payment profile, and lifetime value.",
    position: { x: 440, y: 560 },
    coverage: "95.8%",
    coverageDetail: "(627 / 654 runs)",
    riskScore: 0.06,
    riskLevel: "Low",
    stability: "+0.8%",
    transitions: [
      { action: "REFUND PENDING", toId: "refund_pending", label: "REFUND PENDING", count: 610, percent: "93.3%", kind: "observed" },
    ],
    selectedAction: {
      name: "fetch_crm_profile",
      description: "Reads CRM customer record and risk flags.",
      usedIn: "654 runs",
      successRate: "98.8%",
      avgLatency: "115ms",
    },
  },
  verify_eligibility: {
    id: "verify_eligibility",
    label: "VERIFY ELIGIBILITY",
    line1: "VERIFY",
    line2: "ELIGIBILITY",
    runs: 521,
    iconName: "FileCheck",
    stateId: "S_VERIFY_ELIGIBILITY",
    type: "Decision",
    category: "Policy",
    firstSeen: "Apr 19, 2025 10:11",
    lastSeen: "Apr 28, 2025 12:30",
    totalRuns: 521,
    successRate: "96.4%",
    description: "Evaluates 30-day return window and product condition eligibility.",
    position: { x: 440, y: 180 },
    coverage: "94.6%",
    coverageDetail: "(493 / 521 runs)",
    riskScore: 0.11,
    riskLevel: "Low",
    stability: "+0.2%",
    transitions: [
      { action: "OFFER REPLACEMENT", toId: "offer_replacement", label: "OFFER REPLACEMENT", count: 312, percent: "59.9%", kind: "predicted" },
      { action: "REFUND PENDING", toId: "refund_pending", label: "REFUND PENDING", count: 180, percent: "34.5%", kind: "observed" },
    ],
    selectedAction: {
      name: "check_policy_rules",
      description: "Evaluates refund eligibility matrix.",
      usedIn: "521 runs",
      successRate: "97.5%",
      avgLatency: "85ms",
    },
  },
  offer_replacement: {
    id: "offer_replacement",
    label: "OFFER REPLACEMENT",
    line1: "OFFER",
    line2: "REPLACEMENT",
    runs: 312,
    iconName: "Package",
    stateId: "S_OFFER_REPLACEMENT",
    type: "Action",
    category: "Policy",
    firstSeen: "Apr 19, 2025 11:00",
    lastSeen: "Apr 28, 2025 13:02",
    totalRuns: 312,
    successRate: "89.4%",
    description: "Proposes replacement item or store credit before processing cash refund.",
    position: { x: 670, y: 180 },
    coverage: "88.1%",
    coverageDetail: "(275 / 312 runs)",
    riskScore: 0.35,
    riskLevel: "Medium",
    stability: "-1.1%",
    transitions: [
      { action: "SEND CONFIRMATION", toId: "send_confirmation", label: "SEND CONFIRMATION", count: 210, percent: "67.3%", kind: "predicted" },
      { action: "REFUND PENDING", toId: "refund_pending", label: "REFUND PENDING", count: 95, percent: "30.4%", kind: "predicted" },
    ],
    selectedAction: {
      name: "dispatch_upsell_offer",
      description: "Generates alternative compensation options.",
      usedIn: "312 runs",
      successRate: "94.2%",
      avgLatency: "70ms",
    },
  },
  refund_pending: {
    id: "refund_pending",
    label: "REFUND PENDING",
    line1: "REFUND",
    line2: "PENDING",
    runs: 428,
    iconName: "CreditCard",
    stateId: "S_REFUND_PENDING",
    type: "Action",
    category: "Finance",
    firstSeen: "Apr 18, 2025 09:00",
    lastSeen: "Apr 28, 2025 13:02",
    totalRuns: 428,
    successRate: "72.9%",
    description: "Refund has been approved and is awaiting payment provider confirmation.",
    position: { x: 550, y: 380 },
    coverage: "92.1%",
    coverageDetail: "(392 / 425 runs)",
    riskScore: 0.31,
    riskLevel: "Medium",
    stability: "+2.4%",
    transitions: [
      { action: "PROCESS REFUND", toId: "process_refund", label: "PROCESS REFUND", count: 312, percent: "72.9%", kind: "observed" },
      { action: "PAYMENT FAILED", toId: "payment_failed", label: "PAYMENT FAILED", count: 87, percent: "20.3%", kind: "verified" },
      { action: "ESCALATE TO HUMAN", toId: "escalate_to_human", label: "ESCALATE TO HUMAN", count: 18, percent: "4.2%", kind: "predicted" },
      { action: "TIMEOUT", toId: "timeout", label: "TIMEOUT", count: 6, percent: "1.4%", kind: "verified" },
      { action: "USER CANCELLED", toId: "user_cancelled", label: "USER CANCELLED", count: 5, percent: "1.2%", kind: "protected" },
    ],
    selectedAction: {
      name: "initiate_refund",
      description: "Calls payment provider to create a refund.",
      usedIn: "428 runs",
      successRate: "95.6%",
      avgLatency: "1.2s",
    },
  },
  send_confirmation: {
    id: "send_confirmation",
    label: "SEND CONFIRMATION",
    line1: "SEND",
    line2: "CONFIRMATION",
    runs: 389,
    iconName: "Mail",
    stateId: "S_SEND_CONFIRMATION",
    type: "Action",
    category: "Notification",
    firstSeen: "Apr 18, 2025 09:20",
    lastSeen: "Apr 28, 2025 13:04",
    totalRuns: 389,
    successRate: "99.2%",
    description: "Transmits email and in-app receipt confirmation to customer.",
    position: { x: 910, y: 180 },
    coverage: "98.5%",
    coverageDetail: "(383 / 389 runs)",
    riskScore: 0.04,
    riskLevel: "Low",
    stability: "+0.3%",
    transitions: [
      { action: "RESOLVE", toId: "resolve", label: "RESOLVE", count: 385, percent: "99.0%", kind: "observed" },
    ],
    selectedAction: {
      name: "send_receipt_email",
      description: "Sends automated receipt template via transactional mail service.",
      usedIn: "389 runs",
      successRate: "99.5%",
      avgLatency: "80ms",
    },
  },
  process_refund: {
    id: "process_refund",
    label: "PROCESS REFUND",
    line1: "PROCESS",
    line2: "REFUND",
    runs: 310,
    iconName: "CreditCard",
    stateId: "S_PROCESS_REFUND",
    type: "Process",
    category: "Finance",
    firstSeen: "Apr 18, 2025 09:12",
    lastSeen: "Apr 28, 2025 13:03",
    totalRuns: 310,
    successRate: "96.8%",
    description: "Stripe API interaction successfully settling refund ledger transaction.",
    position: { x: 740, y: 380 },
    coverage: "97.1%",
    coverageDetail: "(301 / 310 runs)",
    riskScore: 0.14,
    riskLevel: "Low",
    stability: "+2.1%",
    transitions: [
      { action: "SEND CONFIRMATION", toId: "send_confirmation", label: "SEND CONFIRMATION", count: 285, percent: "91.9%", kind: "observed" },
      { action: "PAYMENT FAILED", toId: "payment_failed", label: "PAYMENT FAILED", count: 15, percent: "4.8%", kind: "verified" },
      { action: "USER CANCELLED", toId: "user_cancelled", label: "USER CANCELLED", count: 10, percent: "3.2%", kind: "protected" },
    ],
    selectedAction: {
      name: "execute_payment_settlement",
      description: "Dispatches refund token payload to merchant gateway.",
      usedIn: "310 runs",
      successRate: "98.4%",
      avgLatency: "350ms",
    },
  },
  payment_failed: {
    id: "payment_failed",
    label: "PAYMENT FAILED",
    line1: "PAYMENT",
    line2: "FAILED",
    runs: 87,
    iconName: "AlertTriangle",
    stateId: "S_PAYMENT_FAILED",
    type: "Failure",
    category: "Finance",
    firstSeen: "Apr 19, 2025 15:30",
    lastSeen: "Apr 28, 2025 11:45",
    totalRuns: 87,
    successRate: "0.0%",
    isFailure: true,
    description: "Payment gateway rejected refund (expired card, dispute hold, insufficient ledger balance).",
    position: { x: 700, y: 580 },
    coverage: "74.7%",
    coverageDetail: "(65 / 87 runs)",
    riskScore: 0.82,
    riskLevel: "High",
    stability: "-4.2%",
    transitions: [
      { action: "TIMEOUT", toId: "timeout", label: "TIMEOUT", count: 48, percent: "55.2%", kind: "verified" },
      { action: "ESCALATE TO HUMAN", toId: "escalate_to_human", label: "ESCALATE TO HUMAN", count: 32, percent: "36.8%", kind: "predicted" },
    ],
    selectedAction: {
      name: "handle_gateway_error",
      description: "Categorizes rejection error code and alerts billing queue.",
      usedIn: "87 runs",
      successRate: "0%",
      avgLatency: "210ms",
    },
  },
  timeout: {
    id: "timeout",
    label: "TIMEOUT",
    line1: "TIMEOUT",
    runs: 60,
    iconName: "Clock",
    stateId: "S_TIMEOUT",
    type: "Failure",
    category: "System",
    firstSeen: "Apr 19, 2025 16:10",
    lastSeen: "Apr 28, 2025 10:15",
    totalRuns: 60,
    successRate: "0.0%",
    isFailure: true,
    description: "Network timeout waiting for third-party billing gateway API response.",
    position: { x: 590, y: 700 },
    coverage: "68.3%",
    coverageDetail: "(41 / 60 runs)",
    riskScore: 0.91,
    riskLevel: "High",
    stability: "-5.0%",
    transitions: [
      { action: "ESCALATE TO HUMAN", toId: "escalate_to_human", label: "ESCALATE TO HUMAN", count: 58, percent: "96.7%", kind: "predicted" },
    ],
    selectedAction: {
      name: "trigger_fallback_retry",
      description: "Records network timeout and requests queue re-dispatch.",
      usedIn: "60 runs",
      successRate: "0%",
      avgLatency: "5000ms",
    },
  },
  escalate_to_human: {
    id: "escalate_to_human",
    label: "ESCALATE TO HUMAN",
    line1: "ESCALATE",
    line2: "TO HUMAN",
    runs: 276,
    iconName: "UserCheck",
    stateId: "S_ESCALATE_TO_HUMAN",
    type: "Action",
    category: "Escalation",
    firstSeen: "Apr 18, 2025 12:44",
    lastSeen: "Apr 28, 2025 11:30",
    totalRuns: 276,
    successRate: "82.6%",
    description: "Transfers customer session to Zendesk tier-2 human billing agent.",
    position: { x: 440, y: 700 },
    coverage: "84.1%",
    coverageDetail: "(232 / 276 runs)",
    riskScore: 0.48,
    riskLevel: "Medium",
    stability: "-1.2%",
    transitions: [
      { action: "RESOLVE", toId: "resolve", label: "RESOLVE", count: 228, percent: "82.6%", kind: "observed" },
    ],
    selectedAction: {
      name: "transfer_ticket",
      description: "Packages session summary and creates Zendesk priority ticket.",
      usedIn: "276 runs",
      successRate: "98.9%",
      avgLatency: "250ms",
    },
  },
  user_cancelled: {
    id: "user_cancelled",
    label: "USER CANCELLED",
    line1: "USER",
    line2: "CANCELLED",
    runs: 102,
    iconName: "XCircle",
    stateId: "S_USER_CANCELLED",
    type: "Branch",
    category: "Dialogue",
    firstSeen: "Apr 19, 2025 14:20",
    lastSeen: "Apr 28, 2025 12:00",
    totalRuns: 102,
    successRate: "100.0%",
    description: "Customer chose to keep item and cancelled refund process.",
    position: { x: 890, y: 560 },
    coverage: "95.1%",
    coverageDetail: "(97 / 102 runs)",
    riskScore: 0.11,
    riskLevel: "Low",
    stability: "+0.5%",
    transitions: [
      { action: "RESOLVE", toId: "resolve", label: "RESOLVE", count: 98, percent: "96.1%", kind: "predicted" },
    ],
    selectedAction: {
      name: "record_cancellation",
      description: "Releases pending holds and cleanly concludes session.",
      usedIn: "102 runs",
      successRate: "100%",
      avgLatency: "60ms",
    },
  },
  resolve: {
    id: "resolve",
    label: "RESOLVE",
    line1: "RESOLVE",
    runs: 435,
    iconName: "CheckCircle",
    stateId: "S_RESOLVE",
    type: "Terminal",
    category: "Resolution",
    firstSeen: "Apr 18, 2025 09:25",
    lastSeen: "Apr 28, 2025 13:05",
    totalRuns: 435,
    successRate: "100.0%",
    description: "Support ticket marked resolved. CSAT survey dispatched.",
    position: { x: 930, y: 380 },
    coverage: "99.5%",
    coverageDetail: "(433 / 435 runs)",
    riskScore: 0.01,
    riskLevel: "Low",
    stability: "+0.1%",
    transitions: [],
    selectedAction: {
      name: "conclude_session",
      description: "Archives chat session and triggers customer satisfaction poll.",
      usedIn: "435 runs",
      successRate: "100%",
      avgLatency: "65ms",
    },
  },
};

export const CUSTOMER_SUPPORT_EDGES: ReferenceEdge[] = [
  // User Request & Intent
  { id: "e1", from: "user_request", to: "classify_intent", sourceHandle: "right", targetHandle: "left", kind: "observed" },
  { id: "e2", from: "user_request", to: "small_talk", sourceHandle: "bottom", targetHandle: "top", kind: "predicted" },
  { id: "e3", from: "small_talk", to: "classify_intent", sourceHandle: "top", targetHandle: "bottom", kind: "observed" },

  // Clarification & Orders
  { id: "e4", from: "classify_intent", to: "ask_clarification", sourceHandle: "top", targetHandle: "bottom", kind: "predicted" },
  { id: "e5", from: "classify_intent", to: "lookup_order", sourceHandle: "right", targetHandle: "left", kind: "observed" },
  { id: "e6", from: "ask_clarification", to: "lookup_order", sourceHandle: "right", targetHandle: "top", kind: "predicted" },

  // Order & Customer Lookups
  { id: "e7", from: "lookup_order", to: "verify_eligibility", sourceHandle: "top", targetHandle: "left", kind: "observed" },
  { id: "e8", from: "lookup_order", to: "lookup_customer", sourceHandle: "bottom", targetHandle: "top", kind: "observed" },
  { id: "e9", from: "lookup_customer", to: "refund_pending", sourceHandle: "right", targetHandle: "left", kind: "observed" },

  // Eligibility & Replacement
  { id: "e10", from: "verify_eligibility", to: "offer_replacement", sourceHandle: "right", targetHandle: "left", kind: "predicted" },
  { id: "e11", from: "verify_eligibility", to: "refund_pending", sourceHandle: "bottom", targetHandle: "top", kind: "observed" },
  { id: "e12", from: "offer_replacement", to: "send_confirmation", sourceHandle: "right", targetHandle: "left", kind: "predicted" },
  { id: "e13", from: "offer_replacement", to: "refund_pending", sourceHandle: "bottom", targetHandle: "top", kind: "predicted" },

  // Central Refund Pending Hub
  { id: "e14", from: "refund_pending", to: "process_refund", sourceHandle: "right", targetHandle: "left", kind: "observed", runs: 312, percent: "72.9%" },
  { id: "e15", from: "refund_pending", to: "payment_failed", sourceHandle: "bottom", targetHandle: "top", kind: "verified", runs: 87, percent: "20.3%" },
  { id: "e16", from: "refund_pending", to: "escalate_to_human", sourceHandle: "bottom", targetHandle: "top", kind: "predicted", runs: 18, percent: "4.2%" },
  { id: "e17", from: "refund_pending", to: "timeout", sourceHandle: "bottom", targetHandle: "top", kind: "verified", runs: 6, percent: "1.4%" },
  { id: "e18", from: "refund_pending", to: "user_cancelled", sourceHandle: "bottom", targetHandle: "left", kind: "protected", runs: 5, percent: "1.2%" },

  // Process Refund to Confirm / Fail / Cancel
  { id: "e19", from: "process_refund", to: "send_confirmation", sourceHandle: "top", targetHandle: "bottom", kind: "observed" },
  { id: "e20", from: "process_refund", to: "payment_failed", sourceHandle: "bottom", targetHandle: "top", kind: "verified" },
  { id: "e21", from: "process_refund", to: "user_cancelled", sourceHandle: "bottom", targetHandle: "top", kind: "protected" },

  // Terminal Flows
  { id: "e22", from: "send_confirmation", to: "resolve", sourceHandle: "bottom", targetHandle: "top", kind: "observed" },
  { id: "e23", from: "user_cancelled", to: "resolve", sourceHandle: "top", targetHandle: "bottom", kind: "predicted" },
  { id: "e24", from: "payment_failed", to: "timeout", sourceHandle: "bottom", targetHandle: "top", kind: "verified" },
  { id: "e25", from: "payment_failed", to: "escalate_to_human", sourceHandle: "bottom", targetHandle: "right", kind: "predicted" },
  { id: "e26", from: "timeout", to: "escalate_to_human", sourceHandle: "left", targetHandle: "right", kind: "predicted" },
  { id: "e27", from: "escalate_to_human", to: "resolve", sourceHandle: "right", targetHandle: "bottom", kind: "observed" },
];

export const CUSTOMER_SUPPORT_TRACE: ReferenceTraceData = {
  runId: "7f3a9c2d",
  timestamp: "Apr 28, 2025 12:41:03",
  stateCount: 18,
  duration: "42.6s",
  status: "Success",
  steps: [
    { id: "s1", nodeId: "user_request", label: "USER REQUEST", time: "0.0s", status: "success" },
    { id: "s2", nodeId: "classify_intent", label: "CLASSIFY INTENT", time: "1.2s", status: "success" },
    { id: "s3", nodeId: "lookup_order", label: "CHECK ORDER", time: "3.4s", status: "success" },
    { id: "s4", nodeId: "lookup_customer", label: "LOOKUP CUSTOMER", time: "5.1s", status: "success" },
    { id: "s5", nodeId: "refund_pending", label: "REFUND PENDING", time: "8.7s", status: "success" },
    { id: "s6", nodeId: "process_refund", label: "PROCESS REFUND", time: "12.3s", status: "success" },
    { id: "s7", nodeId: "send_confirmation", label: "SEND CONFIRMATION", time: "28.1s", status: "success" },
    { id: "s8", nodeId: "resolve", label: "RESOLVE", time: "42.6s", status: "success" },
  ],
};

/* ========================================================================= */
/*  3. HELPER LOOKUP & DEFAULT EXPORTS                                       */
/* ========================================================================= */

export function getAgentReferenceData(agent: string = "sre-agent") {
  if (agent === "refund-agent" || agent.toLowerCase().includes("support")) {
    return {
      agentName: "Customer Support Agent",
      nodes: CUSTOMER_SUPPORT_NODES,
      edges: CUSTOMER_SUPPORT_EDGES,
      trace: CUSTOMER_SUPPORT_TRACE,
      initialSelected: "refund_pending",
    };
  }
  return {
    agentName: "SRE Agent",
    nodes: SRE_AGENT_NODES,
    edges: SRE_AGENT_EDGES,
    trace: SRE_AGENT_TRACE,
    initialSelected: "rollback_succeeded",
  };
}

// Default export aliases: SRE agent is the primary agent
export const AGENTGARAGE_NODES = SRE_AGENT_NODES;
export const AGENTGARAGE_EDGES = SRE_AGENT_EDGES;
export const AGENTGARAGE_TRACE = SRE_AGENT_TRACE;
